pipeline {
    agent none
    tools {
    maven '/usr/share/maven'
    }
        
    
    stages {
        stage('build & SonarQube analysis') {
            steps {
                withSonarQubeEnv('sonar')
                sh 'mvn -B -DskipTests clean package sonar:sonar'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                
                
            }
        }
    }
}
